import type { IDropdownOptions, IJob, IJobCategory } from './types';

export const jobCategories: IJobCategory[] = [
  {
    id: 1,
    title: 'Customer Services',
  },
  {
    id: 2,
    title: 'Project Management',
  },
  {
    id: 3,
    title: 'Development',
  },
  {
    id: 4,
    title: 'Design',
  },
  {
    id: 5,
    title: 'Marketing',
  },
  {
    id: 6,
    title: 'Accounting/Finance',
  },
];

export const jobs: IJob[] = [
  {
    id: 'job-001',
    title: 'Frontend Developer',
    description:
      'Build and maintain user-facing features using React and TypeScript.',
    company: 'TechCorp Inc.',
    location: 'San Francisco, CA',
    salaryFrom: 100000,
    salaryTo: 150000,
    employmentType: 'Full-time',
    postedDate: new Date('2025-07-01'),
    skillsRequired: ['React', 'JavaScript', 'TypeScript', 'CSS'],
    remote: true,
    experienceLevel: 'Mid',
    industry: 'Technology',
  },
  {
    id: 'job-002',
    title: 'Backend Engineer',
    description:
      'Develop and maintain scalable backend services using Node.js and PostgreSQL.',
    company: 'DataStream Solutions',
    location: 'Austin, TX',
    salaryFrom: 110000,
    salaryTo: 165000,
    employmentType: 'Full-time',
    postedDate: new Date('2025-06-28'),
    skillsRequired: ['Node.js', 'Express', 'PostgreSQL', 'Docker'],
    remote: false,
    experienceLevel: 'Mid',
    industry: 'Software',
  },
  {
    id: 'job-003',
    title: 'UI/UX Designer',
    description:
      'Design intuitive interfaces and improve user experience across web and mobile.',
    company: 'BrightDesign Co.',
    location: 'Remote',
    salaryFrom: 90000,
    salaryTo: 120000,
    employmentType: 'Freelance',
    postedDate: new Date('2025-07-03'),
    skillsRequired: ['Figma', 'Sketch', 'User Research'],
    remote: true,
    experienceLevel: 'Mid',
    industry: 'Design',
  },
  {
    id: 'job-004',
    title: 'Project Manager',
    description:
      'Lead software development projects and coordinate cross-functional teams.',
    company: 'AgileTech Solutions',
    location: 'Chicago, IL',
    salaryFrom: 95000,
    salaryTo: 105000,
    employmentType: 'Full-time',
    postedDate: new Date('2025-06-30'),
    skillsRequired: ['Agile', 'Scrum', 'JIRA', 'Leadership'],
    remote: false,
    experienceLevel: 'Senior',
    industry: 'IT Services',
  },
  {
    id: 'job-005',
    title: 'Data Analyst',
    description: 'Analyze business data to help drive strategic decisions.',
    company: 'MarketIQ',
    location: 'Boston, MA',
    salaryFrom: 80000,
    salaryTo: 120000,
    employmentType: 'Full-time',
    postedDate: new Date('2025-07-05'),
    skillsRequired: ['SQL', 'Python', 'Power BI', 'Excel'],
    remote: true,
    experienceLevel: 'Entry',
    industry: 'Finance',
  },
  {
    id: 'job-006',
    title: 'DevOps Engineer',
    description: 'Implement CI/CD pipelines and manage cloud infrastructure.',
    company: 'Cloudify',
    location: 'Denver, CO',
    salaryFrom: 130000,
    salaryTo: 150000,
    employmentType: 'Full-time',
    postedDate: new Date('2025-07-02'),
    skillsRequired: ['AWS', 'Terraform', 'Kubernetes', 'CI/CD'],
    remote: true,
    experienceLevel: 'Mid',
    industry: 'Cloud Services',
  },
  {
    id: 'job-007',
    title: 'Content Writer',
    description:
      'Create high-quality content for blogs, newsletters, and social media.',
    company: 'InspireWords Media',
    location: 'Remote',
    salaryFrom: 85000,
    salaryTo: 95000,
    employmentType: 'Part-time',
    postedDate: new Date('2025-07-01'),
    skillsRequired: ['SEO', 'Copywriting', 'WordPress'],
    remote: true,
    experienceLevel: 'Entry',
    industry: 'Media',
  },
  {
    id: 'job-008',
    title: 'Machine Learning Engineer',
    description: 'Develop predictive models and deploy ML pipelines.',
    company: 'Neurolytics AI',
    location: 'New York, NY',
    salaryFrom: 150000,
    salaryTo: 195000,
    employmentType: 'Full-time',
    postedDate: new Date('2025-07-06'),
    skillsRequired: ['Python', 'TensorFlow', 'Pandas', 'AWS SageMaker'],
    remote: false,
    experienceLevel: 'Senior',
    industry: 'Artificial Intelligence',
  },
  {
    id: 'job-009',
    title: 'Technical Support Specialist',
    description:
      'Provide Level 2 support to customers using our SaaS platform.',
    company: 'HelpBridge',
    location: 'Phoenix, AZ',
    salaryFrom: 55000,
    salaryTo: 85000,
    employmentType: 'Full-time',
    postedDate: new Date('2025-07-04'),
    skillsRequired: ['Customer Support', 'Troubleshooting', 'CRM Tools'],
    remote: false,
    experienceLevel: 'Entry',
    industry: 'Customer Support',
  },
  {
    id: 'job-010',
    title: 'Intern - Software Engineering',
    description:
      'Assist in developing new features and fixing bugs under mentorship.',
    company: 'StartNova',
    location: 'Seattle, WA',
    salaryFrom: 80000,
    salaryTo: 85000,
    employmentType: 'Internship',
    postedDate: new Date('2025-06-25'),
    skillsRequired: ['JavaScript', 'Git', 'Team Collaboration'],
    remote: true,
    experienceLevel: 'Entry',
    industry: 'Startup',
  },
];

export const dropdownOptions: IDropdownOptions[] = [
  {
    id: 1,
    text: 'Full-Time',
  },
  {
    id: 2,
    text: 'Part-Time',
  },
  {
    id: 3,
    text: 'Internship',
  },
  {
    id: 4,
    text: 'Freelance',
  },
];
